// DO NOT EDIT THIS FILE MANUALLY
// Wed Aug 17 2022 16:07:55 GMT-0500 (Central Daylight Time)
declare let udg_AbilityTest: unknown | undefined;
declare let udg_AbilityTestArray: unknown[] | undefined;
declare let gg_rct_Region_000: rect | undefined;
declare let gg_cam_Camera_001: camerasetup | undefined;
declare let gg_snd_SoulPreservation: sound | undefined;
declare let gg_trg_Untitled_Trigger_001: trigger | undefined;
declare let gg_unit_Hblm_0000: unit | undefined;
declare let gg_unit_Obla_0002: unit | undefined;
declare let gg_item_ratf_0004: item | undefined;
declare let gg_dest_LTbr_0000: destructable | undefined;
